const questionsEasy = [
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'What does the Prt Sc button do?',
    correct_answer:
      'Captures what&#039;s on the screen and copies it to your clipboard',
    incorrect_answers: [
      'Nothing',
      'Saves a .png file of what&#039;s on the screen in your screenshots folder in photos',
      'Closes all windows',
    ],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'What amount of bits commonly equals one byte?',
    correct_answer: '8',
    incorrect_answers: ['1', '2', '64'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: '&quot;HTML&quot; stands for Hypertext Markup Language.',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'Time on Computers is measured via the EPOX System.',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'Ada Lovelace is often considered the first computer programmer.',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'What is the domain name for the country Tuvalu?',
    correct_answer: '.tv',
    incorrect_answers: ['.tu', '.tt', '.tl'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'Pointers were not used in the original C programming language; they were added later on in C++.',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'The logo for Snapchat is a Bell.',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'What does the &quot;MP&quot; stand for in MP3?',
    correct_answer: 'Moving Picture',
    incorrect_answers: ['Music Player', 'Multi Pass', 'Micro Point'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'The numbering system with a radix of 16 is more commonly referred to as ',
    correct_answer: 'Hexidecimal',
    incorrect_answers: ['Binary', 'Duodecimal', 'Octal'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'What is the most preferred image format used for logos in the Wikimedia database?',
    correct_answer: '.svg',
    incorrect_answers: ['.png', '.jpeg', '.gif'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'Which company was established on April 1st, 1976 by Steve Jobs, Steve Wozniak and Ronald Wayne?',
    correct_answer: 'Apple',
    incorrect_answers: ['Microsoft', 'Atari', 'Commodore'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'The Windows ME operating system was released in the year 2000.',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'On Twitter, what was the original character limit for a Tweet?',
    correct_answer: '140',
    incorrect_answers: ['120', '160', '100'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'If you were to code software in this language you&#039;d only be able to type 0&#039;s and 1&#039;s.',
    correct_answer: 'Binary',
    incorrect_answers: ['JavaScript', 'C++', 'Python'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'The programming language &#039;Swift&#039; was created to replace what other programming language?',
    correct_answer: 'Objective-C',
    incorrect_answers: ['C#', 'Ruby', 'C++'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'How long is an IPv6 address?',
    correct_answer: '128 bits',
    incorrect_answers: ['32 bits', '64 bits', '128 bytes'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'RAM stands for Random Access Memory.',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'In computing, what does LAN stand for?',
    correct_answer: 'Local Area Network',
    incorrect_answers: [
      'Long Antenna Node',
      'Light Access Node',
      'Land Address Navigation',
    ],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'According to the International System of Units, how many bytes are in a kilobyte of RAM?',
    correct_answer: '1000',
    incorrect_answers: ['512', '1024', '500'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'When Gmail first launched, how much storage did it provide for your email?',
    correct_answer: '1GB',
    incorrect_answers: ['512MB', '5GB', 'Unlimited'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'Linux was first created as an alternative to Windows XP.',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'How many kilobytes in one gigabyte (in decimal)?',
    correct_answer: '1000000',
    incorrect_answers: ['1024', '1000', '1048576'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'How many values can a single byte represent?',
    correct_answer: '256',
    incorrect_answers: ['8', '1', '1024'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'In &quot;Hexadecimal&quot;, what color would be displayed from the color code? &quot;#00FF00&quot;?',
    correct_answer: 'Green',
    incorrect_answers: ['Red', 'Blue', 'Yellow'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'Which computer language would you associate Django framework with?',
    correct_answer: 'Python',
    incorrect_answers: ['C#', 'C++', 'Java'],
  },
]

const questionsMedium = [
  {
    type: 'boolean',
    difficulty: 'medium',
    category: 'Science: Computers',
    question: 'AMD created the first consumer 64-bit processor.',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'Science: Computers',
    question:
      'Nvidia&#039;s headquarters are based in which Silicon Valley city?',
    correct_answer: 'Santa Clara',
    incorrect_answers: ['Palo Alto', 'Cupertino', 'Mountain View'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'Science: Computers',
    question: 'What was the name given to Android 4.3?',
    correct_answer: 'Jelly Bean',
    incorrect_answers: ['Lollipop', 'Nutella', 'Froyo'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'Science: Computers',
    question:
      'Moore&#039;s law originally stated that the number of transistors on a microprocessor chip would double every...',
    correct_answer: 'Year',
    incorrect_answers: ['Four Years', 'Two Years', 'Eight Years'],
  },
  {
    type: 'boolean',
    difficulty: 'medium',
    category: 'Science: Computers',
    question: 'The open source program Redis is a relational database server.',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'Science: Computers',
    question: 'Which of these people was NOT a founder of Apple Inc?',
    correct_answer: 'Jonathan Ive',
    incorrect_answers: ['Steve Jobs', 'Ronald Wayne', 'Steve Wozniak'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'Science: Computers',
    question:
      'In CSS, which of these values CANNOT be used with the &quot;position&quot; property?',
    correct_answer: 'center',
    incorrect_answers: ['static', 'absolute', 'relative'],
  },
  {
    type: 'boolean',
    difficulty: 'medium',
    category: 'Science: Computers',
    question:
      'The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    type: 'boolean',
    difficulty: 'medium',
    category: 'Science: Computers',
    question:
      'All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'Science: Computers',
    question: 'How many bytes are in a single Kibibyte?',
    correct_answer: '1024',
    incorrect_answers: ['2400', '1000', '1240'],
  },
  {
    type: 'boolean',
    difficulty: 'medium',
    category: 'Science: Computers',
    question: 'Android versions are named in alphabetical order.',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    type: 'boolean',
    difficulty: 'medium',
    category: 'Science: Computers',
    question:
      'A Boolean value of &quot;0&quot; represents which of these words?',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'Science: Computers',
    question: 'What is the main CPU is the Sega Mega Drive / Sega Genesis?',
    correct_answer: 'Motorola 68000',
    incorrect_answers: ['Zilog Z80', 'Yamaha YM2612', 'Intel 8088'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'Science: Computers',
    question:
      'Which of the following is a personal computer made by the Japanese company Fujitsu?',
    correct_answer: 'FM-7',
    incorrect_answers: ['PC-9801', 'Xmillennium ', 'MSX'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'Science: Computers',
    question:
      'Laserjet and inkjet printers are both examples of what type of printer?',
    correct_answer: 'Non-impact printer',
    incorrect_answers: [
      'Impact printer',
      'Daisywheel printer',
      'Dot matrix printer',
    ],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'Science: Computers',
    question:
      'The computer OEM manufacturer Clevo, known for its Sager notebook line, is based in which country?',
    correct_answer: 'Taiwan',
    incorrect_answers: [
      'United States',
      'Germany',
      'China (People&#039;s Republic of)',
    ],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'Science: Computers',
    question:
      'In the programming language &quot;Python&quot;, which of these statements would display the string &quot;Hello World&quot; correctly?',
    correct_answer: 'print(&quot;Hello World&quot;)',
    incorrect_answers: [
      'console.log(&quot;Hello World&quot;)',
      'echo &quot;Hello World&quot;',
      'printf(&quot;Hello World&quot;)',
    ],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'Science: Computers',
    question: 'What was the first commerically available computer processor?',
    correct_answer: 'Intel 4004',
    incorrect_answers: ['Intel 486SX', 'TMS 1000', 'AMD AM386'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'Science: Computers',
    question:
      'In programming, the ternary operator is mostly defined with what symbol(s)?',
    correct_answer: '?:',
    incorrect_answers: ['??', 'if then', '?'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'Science: Computers',
    question:
      'What was the first Android version specifically optimized for tablets?',
    correct_answer: 'Honeycomb',
    incorrect_answers: ['Eclair', 'Froyo', 'Marshmellow'],
  },
  {
    type: 'boolean',
    difficulty: 'medium',
    category: 'Science: Computers',
    question: '&quot;Windows NT&quot; is a monolithic kernel.',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    type: 'boolean',
    difficulty: 'medium',
    category: 'Science: Computers',
    question:
      'To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'Science: Computers',
    question: 'When was the programming language &quot;C#&quot; released?',
    correct_answer: '2000',
    incorrect_answers: ['1998', '1999', '2001'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'Science: Computers',
    question: 'How many cores does the Intel i7-6950X have?',
    correct_answer: '10',
    incorrect_answers: ['12', '8', '4'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'Science: Computers',
    question: 'Generally, which component of a computer draws the most power?',
    correct_answer: 'Video Card',
    incorrect_answers: ['Hard Drive', 'Processor', 'Power Supply'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'Science: Computers',
    question:
      'The teapot often seen in many 3D modeling applications is called what?',
    correct_answer: 'Utah Teapot',
    incorrect_answers: ['Pixar Teapot', '3D Teapot', 'Tennessee Teapot'],
  },
  {
    type: 'boolean',
    difficulty: 'medium',
    category: 'Science: Computers',
    question: 'The first dual-core CPU was the Intel Pentium D.',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'Science: Computers',
    question: 'In the server hosting industry IaaS stands for...',
    correct_answer: 'Infrastructure as a Service',
    incorrect_answers: [
      'Internet as a Service',
      'Internet and a Server',
      'Infrastructure as a Server',
    ],
  },
  {
    type: 'boolean',
    difficulty: 'medium',
    category: 'Science: Computers',
    question:
      'The last Windows operating system to be based on the Windows 9x kernel was Windows 98.',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'Science: Computers',
    question: '.rs is the top-level domain for what country?',
    correct_answer: 'Serbia',
    incorrect_answers: ['Romania', 'Russia', 'Rwanda'],
  },
]

const questionsHard = [
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question: 'Which RAID array type is associated with data mirroring?',
    correct_answer: 'RAID 1',
    incorrect_answers: ['RAID 0', 'RAID 10', 'RAID 5'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question: 'What port does HTTP run on?',
    correct_answer: '80',
    incorrect_answers: ['53', '443', '23'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question: 'Which data structure does FILO apply to?',
    correct_answer: 'Stack',
    incorrect_answers: ['Queue', 'Heap', 'Tree'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question: 'What major programming language does Unreal Engine 4 use?',
    correct_answer: 'C++',
    incorrect_answers: ['Assembly', 'C#', 'ECMAScript'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question: 'What internet protocol was documented in RFC 1459?',
    correct_answer: 'IRC',
    incorrect_answers: ['HTTP', 'HTTPS', 'FTP'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question:
      'Which of the following computer components can be built using only NAND gates?',
    correct_answer: 'ALU',
    incorrect_answers: ['CPU', 'RAM', 'Register'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question: 'How many Hz does the video standard PAL support?',
    correct_answer: '50',
    incorrect_answers: ['59', '60', '25'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question:
      'The internet domain .fm is the country-code top-level domain for which Pacific Ocean island nation?',
    correct_answer: 'Micronesia',
    incorrect_answers: ['Fiji', 'Tuvalu', 'Marshall Islands'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question:
      'Which of the following is the oldest of these computers by release date?',
    correct_answer: 'TRS-80',
    incorrect_answers: ['Commodore 64', 'ZX Spectrum', 'Apple 3'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question:
      'Which of these was the name of a bug found in April 2014 in the publicly available OpenSSL cryptography library?',
    correct_answer: 'Heartbleed',
    incorrect_answers: ['Shellshock', 'Corrupted Blood', 'Shellscript'],
  },
  {
    type: 'boolean',
    difficulty: 'hard',
    category: 'Science: Computers',
    question: 'DHCP stands for Dynamic Host Configuration Port.',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question:
      'What is the name given to layer 4 of the Open Systems Interconnection (ISO) model?',
    correct_answer: 'Transport',
    incorrect_answers: ['Session', 'Data link', 'Network'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question:
      'Which of these names was an actual codename for a cancelled Microsoft project?',
    correct_answer: 'Neptune',
    incorrect_answers: ['Enceladus', 'Pollux', 'Saturn'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question: 'The acronym &quot;RIP&quot; stands for which of these?',
    correct_answer: 'Routing Information Protocol',
    incorrect_answers: [
      'Runtime Instance Processes',
      'Regular Interval Processes',
      'Routine Inspection Protocol',
    ],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question:
      'According to DeMorgan&#039;s Theorem, the Boolean expression (AB)&#039; is equivalent to:',
    correct_answer: 'A&#039; + B&#039;',
    incorrect_answers: [
      'A&#039;B + B&#039;A',
      'A&#039;B&#039;',
      'AB&#039; + AB',
    ],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question:
      'Which of these is not a layer in the OSI model for data communications?',
    correct_answer: 'Connection Layer',
    incorrect_answers: [
      'Application Layer',
      'Transport Layer',
      'Physical Layer',
    ],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question:
      'Who is the original author of the realtime physics engine called PhysX?',
    correct_answer: 'NovodeX',
    incorrect_answers: ['Ageia', 'Nvidia', 'AMD'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question: 'Who is the founder of Palantir?',
    correct_answer: 'Peter Thiel',
    incorrect_answers: ['Mark Zuckerberg', 'Marc Benioff', 'Jack Dorsey'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question:
      'What is the name of the process that sends one qubit of information using two bits of classical information?',
    correct_answer: 'Quantum Teleportation',
    incorrect_answers: [
      'Super Dense Coding',
      'Quantum Entanglement',
      'Quantum Programming',
    ],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question: 'What vulnerability ranked #1 on the OWASP Top 10 in 2013?',
    correct_answer: 'Injection ',
    incorrect_answers: [
      'Broken Authentication',
      'Cross-Site Scripting',
      'Insecure Direct Object References',
    ],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question: 'Who invented the &quot;Spanning Tree Protocol&quot;?',
    correct_answer: 'Radia Perlman',
    incorrect_answers: ['Paul Vixie', 'Vint Cerf', 'Michael Roberts'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question:
      'Dutch computer scientist Mark Overmars is known for creating which game development engine?',
    correct_answer: 'Game Maker',
    incorrect_answers: ['Stencyl', 'Construct', 'Torque 2D'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question:
      'The Harvard architecture for micro-controllers added which additional bus?',
    correct_answer: 'Instruction',
    incorrect_answers: ['Address', 'Data', 'Control'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question: 'Which kind of algorithm is Ron Rivest not famous for creating?',
    correct_answer: 'Secret sharing scheme',
    incorrect_answers: [
      'Hashing algorithm',
      'Asymmetric encryption',
      'Stream cipher',
    ],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question:
      'What does the International System of Quantities refer 1024 bytes as?',
    correct_answer: 'Kibibyte',
    incorrect_answers: ['Kylobyte', 'Kilobyte', 'Kelobyte'],
  },
  {
    type: 'boolean',
    difficulty: 'hard',
    category: 'Science: Computers',
    question:
      'The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question: 'What was the name of the first Bulgarian personal computer?',
    correct_answer: 'IMKO-1',
    incorrect_answers: ['Pravetz 82', 'Pravetz 8D', 'IZOT 1030'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question:
      'Which of these is not a key value of Agile software development?',
    correct_answer: 'Comprehensive documentation',
    incorrect_answers: [
      'Individuals and interactions',
      'Customer collaboration',
      'Responding to change',
    ],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question:
      'What was the name of the security vulnerability found in Bash in 2014?',
    correct_answer: 'Shellshock',
    incorrect_answers: ['Heartbleed', 'Bashbug', 'Stagefright'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'Science: Computers',
    question:
      'What is the codename of the eighth generation Intel Core micro-architecture launched in October 2017?',
    correct_answer: 'Coffee Lake',
    incorrect_answers: ['Sandy Bridge', 'Skylake', 'Broadwell'],
  },
]
