const questions = [
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'What does the Prt Sc button do?',
    correct_answer:
      'Captures what&#039;s on the screen and copies it to your clipboard',
    incorrect_answers: [
      'Nothing',
      'Saves a .png file of what&#039;s on the screen in your screenshots folder in photos',
      'Closes all windows',
    ],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'What amount of bits commonly equals one byte?',
    correct_answer: '8',
    incorrect_answers: ['1', '2', '64'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: '&quot;HTML&quot; stands for Hypertext Markup Language.',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'Time on Computers is measured via the EPOX System.',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'Ada Lovelace is often considered the first computer programmer.',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'What is the domain name for the country Tuvalu?',
    correct_answer: '.tv',
    incorrect_answers: ['.tu', '.tt', '.tl'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'Pointers were not used in the original C programming language; they were added later on in C++.',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'The logo for Snapchat is a Bell.',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'What does the &quot;MP&quot; stand for in MP3?',
    correct_answer: 'Moving Picture',
    incorrect_answers: ['Music Player', 'Multi Pass', 'Micro Point'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'The numbering system with a radix of 16 is more commonly referred to as ',
    correct_answer: 'Hexidecimal',
    incorrect_answers: ['Binary', 'Duodecimal', 'Octal'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'What is the most preferred image format used for logos in the Wikimedia database?',
    correct_answer: '.svg',
    incorrect_answers: ['.png', '.jpeg', '.gif'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'Which company was established on April 1st, 1976 by Steve Jobs, Steve Wozniak and Ronald Wayne?',
    correct_answer: 'Apple',
    incorrect_answers: ['Microsoft', 'Atari', 'Commodore'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'The Windows ME operating system was released in the year 2000.',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'On Twitter, what was the original character limit for a Tweet?',
    correct_answer: '140',
    incorrect_answers: ['120', '160', '100'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'If you were to code software in this language you&#039;d only be able to type 0&#039;s and 1&#039;s.',
    correct_answer: 'Binary',
    incorrect_answers: ['JavaScript', 'C++', 'Python'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'The programming language &#039;Swift&#039; was created to replace what other programming language?',
    correct_answer: 'Objective-C',
    incorrect_answers: ['C#', 'Ruby', 'C++'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'How long is an IPv6 address?',
    correct_answer: '128 bits',
    incorrect_answers: ['32 bits', '64 bits', '128 bytes'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'RAM stands for Random Access Memory.',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'In computing, what does LAN stand for?',
    correct_answer: 'Local Area Network',
    incorrect_answers: [
      'Long Antenna Node',
      'Light Access Node',
      'Land Address Navigation',
    ],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'According to the International System of Units, how many bytes are in a kilobyte of RAM?',
    correct_answer: '1000',
    incorrect_answers: ['512', '1024', '500'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'When Gmail first launched, how much storage did it provide for your email?',
    correct_answer: '1GB',
    incorrect_answers: ['512MB', '5GB', 'Unlimited'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'Linux was first created as an alternative to Windows XP.',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'How many kilobytes in one gigabyte (in decimal)?',
    correct_answer: '1000000',
    incorrect_answers: ['1024', '1000', '1048576'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question: 'How many values can a single byte represent?',
    correct_answer: '256',
    incorrect_answers: ['8', '1', '1024'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'In &quot;Hexadecimal&quot;, what color would be displayed from the color code? &quot;#00FF00&quot;?',
    correct_answer: 'Green',
    incorrect_answers: ['Red', 'Blue', 'Yellow'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'Science: Computers',
    question:
      'Which computer language would you associate Django framework with?',
    correct_answer: 'Python',
    incorrect_answers: ['C#', 'C++', 'Java'],
  },
]
